### ISSUE TITLE
WARNING: Mochi requires at least 4xH100 GPU

### ISSUE THREAD

**Issue by mmtmn** [genmoai/models#17]
it would be nice to include this in the documentation (README.md)...

Edit: has been included in the documentation and it seems like the maintainers are trying to reduce the hardware requirements. A repository that has been self heart emoji has been posted bellow, I have no idea how safe or legit it is and won't be testing until confirmed by more trusted sources.

**Comment by johnwick123f** [comment]
There are much more optimized versions now that can run in 24gb vram gpus now.

https://github.com/kijai/ComfyUI-MochiWrapper

**Comment by mmtmn** [comment]
> There are much more optimized versions now that can run in 24gb vram gpus now.
> 
> https://github.com/kijai/ComfyUI-MochiWrapper

hm, I don't know about this.. seems too good to be true

The repository has way more issues then genmoai repository..

If he did find a way to optimize this repository, I'd rather just wait for genmoai's team to optimize this repository

Also, from those that claimed to get it work, the videos are not that good and take too long. 

I'll wait for some reputable sources to battle test that repository before checking it out

Regardless, feels a bit like virtual reality headsets first generation, worth skipping until it improves in important aspects such as time to generate and quality

**Comment by mmtmn** [comment]
@vedantroy @akbar-genmo @ved-genmo  any confirmation if this ComfyUI is legit?

**Comment by mmtmn** [comment]
also, thanks for adding this
![image](https://github.com/user-attachments/assets/5121928d-dc88-48cc-a18b-761a40dabc19)
I tagged you guys in case this solves the hardware requirement

**Comment by johnwick123f** [comment]
@mmtmn lol, No need to be so skeptical, Kijai is an excellent guy who is very well known for making optimized comfyui nodes for people. You can also check the repo has 400+ stars and he has many popular repos. Also, why the videos don’t look as good as the official website is for a few reasons.

1. Most people are using fp8 version since is far faster and takes less vram. This will make mochi lose a slight bit of detail.
2. The official genmo website uses an extra upscaler/enhancer. You can also use upscalers/enhancers if you want but most people don’t.
3. They are generating with 50 steps instead of 200 which the official website does I believe. It’s 4x faster and close in terms of quality but will have a few morphing issues.


I believe this repo isn’t supposed to be a final solution for inference but rather like a basic working implementation. Even the readme.md says this.

**Comment by johnwick123f** [comment]
@mmtmn This repository also references the wrapper now, and they used some code from the wrapper for sdpa too.

The wrapper is still much more optimized, it supports extra optimization techniques like cublas ops, gguf q8, sageattn, flash attn. You can also use diffusers now, it’s not as optimized but should be easier to load the models.

**Comment by ved-genmo** [comment]
The ComfyUI repository is legit. This repository has upstreamed a bunch of changes from that repository (sage attention, and tiled decoding -- we already had flash attention natively).

**Comment by mmtmn** [comment]
@ved-genmo thank you for letting me know its legit.
@johnwick123f thank you for letting me know about this repository! with the clever cyber security attacks out there, a little bit of a healthy skepticism is always warranted
