### ISSUE TITLE
What is the rule for setting "Number of Frames"?

### ISSUE THREAD

**Issue by ptits** [genmoai/models#37]
AssertionError: t - 1 must be divisible by 6: 5 != 0

ok, i see 

now:

assert x.size(2) >= frames_to_send

please tell us the rule for setting "Number of Frames", for 4 and 8 GPUs

None works except 163

**Comment by ajayjain** [comment]
Since Mochi's VAE downsamples the video by 6x temporally except for the first frame, you need the number of frames T to be 1 more than a multiple of 6. For example, 1, 7, 13, 19, etc.

Also, when running with multiple GPUs, the frames are split across the different GPUs. If you don't have enough frames to process, then the distributed ContextParallelConv3d will hit the assertion error you saw. This is because the layer is trying to send 2 frames between GPUs, but the activation has fewer than 2 frames.

For N GPUs, you need at least 1 + 6 * N frames. I think 91 frames should work with 8 GPUs. Have you tried other configurations? It would be helpful to see what fails since we didn't do extensive testing on short videos.

**Comment by JH-ninjatech** [comment]
Hi @ajayjain I have tried generating 49 frames using 4 GPUs and it throws me error:
![image](https://github.com/user-attachments/assets/35327d1a-4466-4c40-b187-2b54522b9857)
